### PR TITLE
Make maintainers explicit with CODEOWNERS

### PR DESCRIPTION
**Pull request by lpil**
Hello!

We're making maintainers explicit. I've guessed the maintainers here, let me know if this is not right. Thanks!

### CODE REVIEW

**Comment by lsjostro** [comment]
Hello!

Yeah, I'm original author yes, but not with the company anymore. So I'm not sure if you use JWT token validation with perforce still? Talk to @nollbit he might know. Otherwise you can archive the repo I would say, or make a note in the readme that its unmaintained.

**Comment by lpil** [comment]
Oh dear! Thanks for the context @lsjostro ! I'll get this sorted out.

**Review by 0ax1 — APPROVED** [review]

**Comment by 0ax1** [comment]
Note to self: Change master to main.

**Comment by lpil** [comment]
Thanks!

**Pull request merged**
